"""initial: session_logs + user_memories

Revision ID: 0a6105dd91f9
Revises:
Create Date: 2026-05-12 22:20:19.225684

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0a6105dd91f9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room', sa.String(length=255), nullable=False),
    sa.Column('participant', sa.String(length=255), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_logs_participant'), 'session_logs', ['participant'], unique=False)
    op.create_index(op.f('ix_session_logs_room'), 'session_logs', ['room'], unique=False)
    op.create_table('user_memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('risk_profile', sa.String(length=50), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('mentioned_products', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_session_logs_room'), table_name='session_logs')
    op.drop_index(op.f('ix_session_logs_participant'), table_name='session_logs')
    op.drop_table('session_logs')
    # ### end Alembic commands ###
